version: '3'
services:
  web-mpc:
    container_name: web-mpc
    restart: always
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/code
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
