/***************************************************************
 *
 * server/template.js
 *
 * Data field names.
 *
 */

module.exports = {
    "Executive/Senior Level Officials and Managers_Hispanic or Latino Male": 0,
    "Executive/Senior Level Officials and Managers_Hispanic or Latino Female": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male White": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male Black or African American": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male Native Hawaiian or Other Parcific Islander": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male Asian": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male American Indian or Alaska Native": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male Two or more races": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female White": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female Black or African American": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female Native Hawaiian or Other Parcific Islander": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female Asian": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female American Indian or Alaska Native": 0,
    "Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female Two or more races": 0,
    "Executive/Senior Level Officials and Managers_TOTAL Rows": 0,
    "First/Mid-Level Officials and Managers_Hispanic or Latino Male": 0,
    "First/Mid-Level Officials and Managers_Hispanic or Latino Female": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male White": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male Black or African American": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male Native Hawaiian or Other Parcific Islander": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male Asian": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male American Indian or Alaska Native": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male Two or more races": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female White": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female Black or African American": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female Native Hawaiian or Other Parcific Islander": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female Asian": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female American Indian or Alaska Native": 0,
    "First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female Two or more races": 0,
    "First/Mid-Level Officials and Managers_TOTAL Rows": 0,
    "Professionals_Hispanic or Latino Male": 0,
    "Professionals_Hispanic or Latino Female": 0,
    "Professionals_Not-Hispanic or Latino Male White": 0,
    "Professionals_Not-Hispanic or Latino Male Black or African American": 0,
    "Professionals_Not-Hispanic or Latino Male Native Hawaiian or Other Parcific Islander": 0,
    "Professionals_Not-Hispanic or Latino Male Asian": 0,
    "Professionals_Not-Hispanic or Latino Male American Indian or Alaska Native": 0,
    "Professionals_Not-Hispanic or Latino Male Two or more races": 0,
    "Professionals_Not-Hispanic or Latino Female White": 0,
    "Professionals_Not-Hispanic or Latino Female Black or African American": 0,
    "Professionals_Not-Hispanic or Latino Female Native Hawaiian or Other Parcific Islander": 0,
    "Professionals_Not-Hispanic or Latino Female Asian": 0,
    "Professionals_Not-Hispanic or Latino Female American Indian or Alaska Native": 0,
    "Professionals_Not-Hispanic or Latino Female Two or more races": 0,
    "Professionals_TOTAL Rows": 0,
    "TOTAL Cols_Hispanic or Latino Male": 0,
    "TOTAL Cols_Hispanic or Latino Female": 0,
    "TOTAL Cols_Not-Hispanic or Latino Male White": 0,
    "TOTAL Cols_Not-Hispanic or Latino Male Black or African American": 0,
    "TOTAL Cols_Not-Hispanic or Latino Male Native Hawaiian or Other Parcific Islander": 0,
    "TOTAL Cols_Not-Hispanic or Latino Male Asian": 0,
    "TOTAL Cols_Not-Hispanic or Latino Male American Indian or Alaska Native": 0,
    "TOTAL Cols_Not-Hispanic or Latino Male Two or more races": 0,
    "TOTAL Cols_Not-Hispanic or Latino Female White": 0,
    "TOTAL Cols_Not-Hispanic or Latino Female Black or African American": 0,
    "TOTAL Cols_Not-Hispanic or Latino Female Native Hawaiian or Other Parcific Islander": 0,
    "TOTAL Cols_Not-Hispanic or Latino Female Asian": 0,
    "TOTAL Cols_Not-Hispanic or Latino Female American Indian or Alaska Native": 0,
    "TOTAL Cols_Not-Hispanic or Latino Female Two or more races": 0
}
