/***************************************************************
 *
 * server/template.js
 *
 * Data field names.
 *
 */

module.exports = {
    "board_TOTAL_Female Other": 0,
    "board_TOTAL_Female White": 0,
    "board_TOTAL_Male Other": 0,
    "board_TOTAL_Male White": 0,
    "includeBoard_Provide Board of Directors information_yes": 0,
    "includeBoard_Provide Board of Directors information_no": 0,
    "main_Executive/Senior Level Officials and Managers_Hispanic or Latino Male": 0,
    "main_Executive/Senior Level Officials and Managers_Hispanic or Latino Female": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male White": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male Black or African American": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male Native Hawaiian or Other Parcific Islander": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male Asian": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male American Indian or Alaska Native": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Male Two or more races": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female White": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female Black or African American": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female Native Hawaiian or Other Parcific Islander": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female Asian": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female American Indian or Alaska Native": 0,
    "main_Executive/Senior Level Officials and Managers_Not-Hispanic or Latino Female Two or more races": 0,
    "main_Executive/Senior Level Officials and Managers_TOTAL Rows": 0,
    "main_First/Mid-Level Officials and Managers_Hispanic or Latino Male": 0,
    "main_First/Mid-Level Officials and Managers_Hispanic or Latino Female": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male White": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male Black or African American": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male Native Hawaiian or Other Parcific Islander": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male Asian": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male American Indian or Alaska Native": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Male Two or more races": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female White": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female Black or African American": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female Native Hawaiian or Other Parcific Islander": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female Asian": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female American Indian or Alaska Native": 0,
    "main_First/Mid-Level Officials and Managers_Not-Hispanic or Latino Female Two or more races": 0,
    "main_First/Mid-Level Officials and Managers_TOTAL Rows": 0,
    "main_Professionals_Hispanic or Latino Male": 0,
    "main_Professionals_Hispanic or Latino Female": 0,
    "main_Professionals_Not-Hispanic or Latino Male White": 0,
    "main_Professionals_Not-Hispanic or Latino Male Black or African American": 0,
    "main_Professionals_Not-Hispanic or Latino Male Native Hawaiian or Other Parcific Islander": 0,
    "main_Professionals_Not-Hispanic or Latino Male Asian": 0,
    "main_Professionals_Not-Hispanic or Latino Male American Indian or Alaska Native": 0,
    "main_Professionals_Not-Hispanic or Latino Male Two or more races": 0,
    "main_Professionals_Not-Hispanic or Latino Female White": 0,
    "main_Professionals_Not-Hispanic or Latino Female Black or African American": 0,
    "main_Professionals_Not-Hispanic or Latino Female Native Hawaiian or Other Parcific Islander": 0,
    "main_Professionals_Not-Hispanic or Latino Female Asian": 0,
    "main_Professionals_Not-Hispanic or Latino Female American Indian or Alaska Native": 0,
    "main_Professionals_Not-Hispanic or Latino Female Two or more races": 0,
    "main_Professionals_TOTAL Rows": 0,
    "main_TOTAL Cols_Hispanic or Latino Male": 0,
    "main_TOTAL Cols_Hispanic or Latino Female": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Male White": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Male Black or African American": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Male Native Hawaiian or Other Parcific Islander": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Male Asian": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Male American Indian or Alaska Native": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Male Two or more races": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Female White": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Female Black or African American": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Female Native Hawaiian or Other Parcific Islander": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Female Asian": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Female American Indian or Alaska Native": 0,
    "main_TOTAL Cols_Not-Hispanic or Latino Female Two or more races": 0,
    "main_TOTAL Cols_TOTAL Rows": 0,
    "question_Does your company hold events to celebrate diversity and inclusion?_yes": 0, 
    "question_Does your company hold events to celebrate diversity and inclusion?_no": 0, 
    "question_Does your company hold events to celebrate diversity and inclusion?_na": 0, 
    "question_Does your company provide diversity and inclusion education or training for managers, staff or both?_yes": 0,
    "question_Does your company provide diversity and inclusion education or training for managers, staff or both?_no": 0,
    "question_Does your company provide diversity and inclusion education or training for managers, staff or both?_na": 0, 
    "question_Does your management team meet to discuss your organization's diverse workforce or workplace culture?_yes": 0, 
    "question_Does your management team meet to discuss your organization's diverse workforce or workplace culture?_no": 0, 
    "question_Does your management team meet to discuss your organization's diverse workforce or workplace culture?_na": 0, 
    "question_Does your CEO engage in or lead discussions on diversity and inclusion with your management team or with other business executives?_yes": 0,
    "question_Does your CEO engage in or lead discussions on diversity and inclusion with your management team or with other business executives?_no": 0,
    "question_Does your CEO engage in or lead discussions on diversity and inclusion with your management team or with other business executives?_na": 0
}
